### ISSUE TITLE
Reevaluate messages on acceptability

### ISSUE THREAD

**Issue by Fritz-theCat** [yeldiRium/leetbot#437]
Some messages, while meant in good faith, don't feel welcoming and inclusive.
I am thinking of 
"Ihr wollt ein Liebes1337, ihr kriegt mein Rieseng1337!" and
"Die Po1337zei verprügelt {{asshole}} wie einen Menschen mit Migrationshintergrund in den USA! Es geht zwar deutlich zu weit, aber es wird außer {{asshole}} niemand bestraft."

They are at the very least contorversial, and as such not fit for a lighthearted application. These are the two I could think of, but there might be more. I want to find them and discuss how to proceed.

**Comment by yeldiRium** [comment]
Yeah, that is a very valid point. So far I've just accepted any suggestions, since they come from the pool of people who use the application.

But it is nontheless a public project and the humor in here reflects on all of us. (Also I'm not just concerned about optics, some of the lines are genuinely shitty, as you mention.)

It is kind of the point to be rude and vulgar, but discrimination, sexism and similar things should probably be the line.

So here is a small list I think can be removed.

asshole callouts:

- "Die Po1337zei verprügelt {{asshole}} wie einen Menschen mit Migrationshintergrund in den USA! Es geht zwar deutlich zu weit, aber es wird außer {{asshole}} niemand bestraft."

leet reminders:

- "Ihr wollt ein Liebes1337, ihr kriegt mein Rieseng1337!"

timing callouts:

- "Vielen Dank für Ihr Abonement der Hurensohn-Zeitung" (which I think is a pretty funny one, but maybe we can find a better insult than "hurensohn")
- "Axel zu dem Stoll\nfindet dein Gelaber toll.\nAber mach mal keine Welle\ndenn der dood ist nicht sehr helle."

RFC @Fritz-theCat @dotKuro

**Comment by dotKuro** [comment]
I agree. Also can we remove the Leetception reminder? It just isn't funny.
